# Copyright © 2024 Cencora. All rights reserved.
#
# Written by Felix Kahle, A123234, felix.kahle@worldcourier.de

name: Test

on:
  push:
    branches: [ "dev", "main" ]

jobs:
  test:
    name: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add GitHub Package Registry
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/FelixKahle/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal